In [28]:
import numpy as np 
from sklearn.model_selection import train_test_split
X, y = np.arange(10).reshape((5, 2)), range(5)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=4)

In [33]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [35]:
list(y)

[0, 1, 2, 3, 4]

In [29]:
X_train

array([[2, 3],
       [8, 9],
       [4, 5]])

In [30]:
X_test

array([[0, 1],
       [6, 7]])

In [31]:
y_train

[1, 4, 2]

In [32]:
y_test

[0, 3]